import { ReceiptData, ReceiptSettings } from '../../types';
import { useAuth } from '../../lib/AuthContext';

interface Props {
  data: ReceiptData;
  settings: ReceiptSettings;
  receiptRef?: React.RefObject<HTMLDivElement>;
}

const cleanCurrency = (currencyStr: string) => {
  if (!currencyStr) return '₦';
  return currencyStr.split(' ')[0]; 
};

const cleanPrice = (val: any): number => {
  if (typeof val === 'number') return val;
  const cleaned = String(val).replace(/[^0-9.]/g, '');
  const num = parseFloat(cleaned);
  return isNaN(num) ? 0 : num;
};

export default function ReceiptPreview({ data, settings, receiptRef }: Props) {
  const { user } = useAuth();
  const currencySymbol = cleanCurrency(data.currency); 
  
  // LOGIC: Detect if the status is pending for watermark
  const currentStatus = data.status?.toLowerCase();

  const subtotal = data.items.reduce((acc: number, item: any) => 
    acc + (cleanPrice(item.price) * (item.qty || 0)), 0);

  const total = subtotal + (Number(data.shipping) || 0) - (Number(data.discount) || 0);
  const logoLetter = (data.businessName?.charAt(0) || 'R').toUpperCase();

  const zigzagImage = `data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2020%2010%27%20width%3D%2720%27%20height%3D%2710%27%3E%3Cpolygon%20points%3D%270%2C0%2010%2C10%2020%2C0%27%20fill%3D%27white%27%2F%3E%3C%2Fsvg%3E`;

  return (
    <div className="flex justify-center items-start font-sans antialiased p-4 relative">
      <div 
        ref={receiptRef}
        id="receipt-node"
        className="relative text-zinc-900 leading-tight drop-shadow-xl overflow-hidden"
        style={{ width: '320px', backgroundColor: '#ffffff' }}
      >
        {/* PENDING WATERMARK - Shows based on current selection */}
        {currentStatus === 'pending' && (
            <div className="absolute inset-0 z-50 pointer-events-none flex items-center justify-center opacity-[0.1] rotate-[-35deg]">
                <h1 className="text-6xl font-black uppercase tracking-tighter border-8 border-zinc-900 px-4">PENDING</h1>
            </div>
        )}

        {/* ... Background Pattern and Header code (omitted for brevity) ... */}

        <div className="bg-transparent w-full px-5 pt-5 pb-2 relative z-10">
            {/* ... Receipt Content (billed to, items list) ... */}

            <div className="pt-2 border-t-2 border-dashed border-zinc-100 relative z-10">
                <div className="flex justify-between items-center pt-3 border-t border-zinc-100 -mx-5 px-5 py-2 bg-zinc-50/50">
                    <span className="font-black text-sm uppercase tracking-tight text-zinc-700">
                        {currentStatus === 'pending' ? 'TOTAL DUE' : 'TOTAL PAID'}
                    </span>
                    <span className="font-black text-xl font-mono tracking-tight" style={{ color: settings.color }}>
                        {currencySymbol}{total.toLocaleString()}
                    </span>
                </div>
            </div>
            
            <p className="text-center text-[8px] text-zinc-400 mt-4 uppercase tracking-widest font-bold">Generated by MifimnPay</p>
        </div>

        <div className="w-full h-[6px] relative z-20" style={{ backgroundImage: `url("${zigzagImage}")`, backgroundSize: '12px 6px', backgroundRepeat: 'repeat-x' }} />
      </div>
    </div>
  );
}
